### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by jbaylies** [ess-m/gen-filters#1]
These filters sound quite nice! I'd like to include most of them in my rig, which I'm planning on selling under some kind of combo apache/reaper-style nagware license... Would that be alright as long as I include a link to this repository somewhere?

**Comment by ess-m** [comment]
Yes – but note that a lot of these filters are ported over from elsewhere. I should update this repo to include direct links to each, but you can still look the sources up fairly easily by following the comments in `/src/filters.genexpr`. They are all ported from sources with a permissible license, so it should all be fine but you may want to double check.
